version: '3.8'

services:
  gateway:
    build:
      context: ./gateway-service
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=db1
      - DATABASE_USER=root
      - DATABASE_PASSWORD=Temporal2021+
      - DATABASE_NAME=auth_user
      - DATABASE_PORT=3306
    depends_on:
      db1:
        condition: service_healthy

  db1:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Temporal2021+
      MYSQL_DATABASE: auth_user
    ports:
      - "3306:3306"
    volumes:
      - db1_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  users:
    build:
      context: ./users-service
    ports:
      - "3002:3002"
    environment:
      - DATABASE_HOST=db2
      - DATABASE_USER=root
      - DATABASE_PASSWORD=Temporal2021+
      - DATABASE_NAME=users
      - DATABASE_PORT=3306
    depends_on:
      db2:
        condition: service_healthy

  db2:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Temporal2021+
      MYSQL_DATABASE: users
    ports:
      - "3307:3306"
    volumes:
      - db2_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  posts:
    build:
      context: ./posts-service
    ports:
      - "3003:3003"
    environment:
      - DATABASE_HOST=db3
      - DATABASE_USER=root
      - DATABASE_PASSWORD=Temporal2021+
      - DATABASE_NAME=posts
      - DATABASE_PORT=3306
    depends_on:
      db3:
        condition: service_healthy

  db3:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Temporal2021+
      MYSQL_DATABASE: posts
    ports:
      - "3308:3306"
    volumes:
      - db3_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db1_data:
  db2_data:
  db3_data:
